Repository graProj/didacto-api, pull requests merged in 2024-08, with the labels that each got.

#59 [#54] 강의생성시 동시성제어
  build.gradle
  src/main/java/com/didacto/common/ErrorDefineCode.java
  src/main/java/com/didacto/config/exception/custom/exception/NetworkException503.java
  src/main/java/com/didacto/config/redis/RedisConfig.java
  src/main/java/com/didacto/config/security/custom/CustomUser.java
  src/main/java/com/didacto/config/security/custom/CustomUserDetailsService.java
  src/main/java/com/didacto/config/security/jwt/TokenProvider.java
  src/main/java/com/didacto/controller/v1/lecture/LectureCommandController.java
  src/main/java/com/didacto/repository/lecture/LectureCustomRepository.java
  src/main/java/com/didacto/repository/lecture/LectureCustomRepositoryImpl.java
  src/main/java/com/didacto/repository/member/MemberRepository.java
  src/main/java/com/didacto/repository/payment/PaymentRepository.java
  src/main/java/com/didacto/service/auth/AuthService.java
  src/main/java/com/didacto/service/lecture/LectureCommandService.java
  src/main/java/com/didacto/service/order/OrderCommandService.java
  src/main/java/com/didacto/service/payment/PaymentService.java
  src/main/resources/static/payment.html
  src/test/java/com/didacto/MemberFactory.java
  src/test/java/com/didacto/controller/v1/member/MemberControllerTest.java
  src/test/java/com/didacto/service/auth/AuthServiceTest.java
  src/test/java/com/didacto/service/lecture/LectureCommandServiceTest.java
  src/test/java/com/didacto/service/lecture/LectureServiceTest.java
  src/test/java/com/didacto/service/member/MemberServiceTest.java
Labels: feat

#66 [#67] 개설한 강좌 조회 api 추가
  src/main/java/com/didacto/controller/v1/lecture/LectureQueryController.java
Labels: feat

#62 [#61] Enrollment 테스트 코드 규칙 작성
  src/main/java/com/didacto/DidactoApplication.java
  src/main/java/com/didacto/config/security/AuthConstant.java
  src/main/java/com/didacto/controller/v1/enrollment/EnrollmentCommandController.java
  src/main/java/com/didacto/service/enrollment/EnrollmentCommandService.java
  src/main/java/com/didacto/service/enrollment/transaction/EnrollmentTransactionService.java
  src/test/java/com/didacto/controller/v1/enrollment/EnrollmentCommandControllerTest.java
  src/test/java/com/didacto/controller/v1/enrollment/EnrollmentCommandControllerTestWithSecurity.java
  src/test/java/com/didacto/controller/v1/enrollment/EnrollmentQueryControllerTest.java
  src/test/java/com/didacto/repository/enrollment/EnrollmentRepositorylTest.java
  src/test/java/com/didacto/service/enrollment/EnrollmentCommandServiceTest.java
  src/test/java/com/didacto/service/enrollment/EnrollmentQueryServiceTest.java
Labels: test

#69 [#68] CI 및 통합 테스트 시 Embedded-Redis 환경 구축
  build.gradle
  src/main/java/com/didacto/config/redis/RedisConfig.java
  src/test/java/com/didacto/config/EmbeddedRedisConfig.java
  src/test/java/com/didacto/repository/enrollment/EnrollmentRepositorylTest.java
  src/test/java/com/didacto/service/enrollment/EnrollmentCommandServiceTest.java
  src/test/java/com/didacto/service/enrollment/EnrollmentQueryServiceTest.java
  src/test/resources/application-test.yml
Labels: chore, env
